SOURCE: MR
TARGET: CT
NUM_WORKERS: 4
FULLY_SUPERVISED: False
DATASETS: 'Cardiac'
TRAIN:
  DA_METHOD: bcutmix_ST_nonemse
  LOGFILE_NAME: 'pretrain'
  MODEL: DeepLabv2
  RESTORE_FROM:   ../pretrained_model/training/DeepLab_resnet_pretrained_imagenet.pth
  EMA_RESTORE_FROM: ../pretrained_model/training/DeepLab_resnet_pretrained_imagenet.pth
  # RESTORE_FROM:   /home/data_backup/zhr_savedmodel/MR2CT_bcutmix_ST_contrastive_boundary_final_10000_smcontra_dim256_queuelen500_temperature1_new507/model_10000.pth
  # EMA_RESTORE_FROM: /home/data_backup/zhr_savedmodel/MR2CT_bcutmix_ST_contrastive_boundary_final_10000_smcontra_dim256_queuelen500_temperature1_new507/model_10000.pth
  # RESTORE_FROM:   /home/data_backup/zhr_savedmodel/MR2CT_bcutmix_ST_contrastive_boundary_final_10000_stcontra_dim256_queuelen500_temperature1_new50_0.013/model_10000.pth
  # EMA_RESTORE_FROM: /home/data_backup/zhr_savedmodel/MR2CT_bcutmix_ST_contrastive_boundary_final_10000_stcontra_dim256_queuelen500_temperature1_new50_0.013/model_10000.pth
  # RESTORE_FROM:   /home/data_backup/zhr_savedmodel/MR2CT_cutmix_ST_ourdice_myweight/model_13000.pth
  # EMA_RESTORE_FROM: /home/data_backup/zhr_savedmodel/MR2CT_cutmix_ST_ourdice_myweight/model_13000.pth
  # CLASS_CENTER_FEA_INIT: /home/zhr/ICME/pretrained_model/training/class_center_feas_Cardiac_MR2CT_13000.npy
  # RESTORE_FROM:   /home/data_backup/zhr_savedmodel/MR2CT_bcutmix_ST_ourdice_myweight/model_10000.pth
  # EMA_RESTORE_FROM: /home/data_backup/zhr_savedmodel/MR2CT_bcutmix_ST_ourdice_myweight/model_10000.pth
  # CLASS_CENTER_FEA_INIT: /home/zhr/ICME/pretrained_model/training/bcutmix_class_center_feas_Cardiac_MR2CT_10000.npy
  # RESTORE_FROM:   /home/data_backup/zhr_savedmodel/MR2CT_bcutmix_ST_new/model_6000.pth
  # EMA_RESTORE_FROM: /home/data_backup/zhr_savedmodel/MR2CT_bcutmix_ST_new/model_6000.pth
  # CLASS_CENTER_FEA_INIT: /home/zhr/ICME/pretrained_model/training/bcutmix_class_center_feas_Cardiac_MR2CT_new_6000.npy

  



  D_TYPE:         Original_D
  D_NORM:          Batch_Norm
  MULTI_LEVEL: True

  OPTIM_G: 'SGD'
  LEARNING_RATE: 0.001
  MOMENTUM: 0.9
  WEIGHT_DECAY: 0.0005

  MAX_ITERS: 50000
  SAVE_PRED_EVERY: 500

  RANDOM_SEED: 1234

  LAMBDA_ADV_MAIN:      0.003
  LAMBDA_ADV_AUX:       0.00002
  LAMBDA_DICE_SRC_MAIN:   1.0
  LAMBDA_DICE_SRC_AUX:    0.1
  LAMBDA_SEG_SRC_MAIN: 1.0
  LAMBDA_SEG_SRC_AUX: 0.1

TEST:
  MODE: best

